/**
 * Builds the Office.js PowerPoint code for a flowchart from a structured steps array.
 * Called by the server after the LLM returns flowchart_steps — never generated by the LLM.
 * Styling (white fill, black border, black text, lead lines, reference numerals) is
 * enforced here, not by the LLM.
 *
 * @param {Array<{ label: string, type: string, ref: string }>} steps
 */
export function buildFlowchartCode(steps) {
  const H = 60;   // height for Process / Terminator
  const DH = 80;  // height for Decision diamond

  const enriched = steps.map((s, i) => {
    const isDecision = s.type === "FlowChartDecision";
    return {
      label: s.label,
      // Render terminators as plain rectangles (no rounded ends)
      type: s.type === "FlowChartTerminator" ? "rectangle" : s.type,
      // Fall back to X02, X04, X06 … if the LLM didn't supply a ref
      ref: s.ref || `X${String((i + 1) * 2).padStart(2, "0")}`,
      h: isDecision ? DH : H,
    };
  });

  return `
(async () => {
  await PowerPoint.run(async (ctx) => {
    let slide;
    try {
      const sel = ctx.presentation.getSelectedSlides?.();
      if (sel) {
        sel.load("items");
        await ctx.sync();
        if (sel.items?.length > 0) slide = sel.items[0];
      }
    } catch (_) {}
    if (!slide) {
      const slides = ctx.presentation.slides;
      slides.load("items");
      await ctx.sync();
      slide = slides.items[0];
    }

    const W = 220, GAP = 32, LEFT = 240;
    const LEAD_LEN = 60, CURVE_DROP = 14;
    const REF_LEFT = LEFT + W + LEAD_LEN + 8;

    const steps = ${JSON.stringify(enriched, null, 4)};

    const shapeRefs = [];
    const connRefs = [];
    let top = 40;
    for (let i = 0; i < steps.length; i++) {
      const s = steps[i];
      const mid = top + Math.round(s.h / 2);

      // Shape: white fill, black border (1.5pt), black text
      const shape = slide.shapes.addGeometricShape(s.type, { left: LEFT, top, width: W, height: s.h });
      shape.fill.setSolidColor("#FFFFFF");
      shape.lineFormat.visible = true;
      shape.lineFormat.color = "#000000";
      shape.lineFormat.weight = 1.5;
      shape.textFrame.verticalAlignment = "middle";
      shape.textFrame.textRange.font.color = "#000000";
      shape.textFrame.textRange.font.size = 12;
      shape.textFrame.textRange.text = s.label;
      shapeRefs.push(shape);

      // Curved lead line: arcs gently downward from the right edge of the shape
      const lead = slide.shapes.addLine("Curve", { left: LEFT + W, top: mid, width: LEAD_LEN, height: CURVE_DROP });
      lead.lineFormat.color = "#000000";
      lead.lineFormat.weight = 1;

      // Reference numeral: positioned at the end of the curved lead line
      const tb = slide.shapes.addTextBox(s.ref, { left: REF_LEFT, top: mid + CURVE_DROP - 14, width: 60, height: 24 });
      tb.fill.setSolidColor("#FFFFFF");
      tb.lineFormat.visible = false;
      tb.textFrame.textRange.font.size = 12;
      tb.textFrame.textRange.font.bold = true;
      tb.textFrame.textRange.font.color = "#000000";

      // Connector line — arrowhead applied in sync 2
      if (i < steps.length - 1) {
        const conn = slide.shapes.addLine("Straight", {
          left: LEFT + Math.round(W / 2),
          top: top + s.h,
          width: 1,
          height: GAP,
        });
        conn.lineFormat.color = "#000000";
        conn.lineFormat.weight = 1.5;
        connRefs.push(conn);
      }

      top += s.h + GAP;
    }

    // ── Sync 1: commit all shapes, lead lines, text boxes, plain connectors ───
    await ctx.sync();

    // ── Sync 2: arrowhead on each connector line (PowerPointApi 1.6+).
    // "arrow" = standard filled triangle arrowhead at the far end of the line.
    // Isolated so a failure (older API set) cannot revert sync 1.
    try {
      for (const conn of connRefs) {
        conn.lineFormat.endArrowheadStyle = "arrow";
      }
      await ctx.sync();
    } catch (_) {}

    // ── Sync 3: paragraph centering (isolated for the same reason) ────────────
    try {
      for (const shape of shapeRefs) {
        shape.textFrame.textRange.paragraphs.getFirst().paragraphFormat.alignment = "center";
      }
      await ctx.sync();
    } catch (_) {}
  });
})()`.trim();
}
